Repository trace4cats/trace4cats-components, pull requests merged in 2021-07, with the labels that each got.

#5 Rework build
  .github/mergify.yml
  .github/release-drafter.yml
  .github/workflows/build.yaml
  .github/workflows/ci.yml
  .github/workflows/clean.yml
  .github/workflows/release-drafter.yml
  README.md
  build.sbt
  ci-release.sbt
  modules/agent-common/src/main/scala/io/janstenpickle/trace4cats/agent/common/AgentTrace.scala
  modules/agent-common/src/main/scala/io/janstenpickle/trace4cats/agent/common/CommonAgent.scala
  modules/agent-kafka/src/main/docker/build.sh
  modules/agent-kafka/src/main/scala/io/janstenpickle/trace4cats/agent/kafka/AgentKafka.scala
  modules/agent/src/main/docker/build.sh
  modules/agent/src/main/scala/io/janstenpickle/trace4cats/agent/Agent.scala
  modules/collector-common/src/main/scala/io/janstenpickle/trace4cats/collector/common/AttributeFiltering.scala
  modules/collector-common/src/main/scala/io/janstenpickle/trace4cats/collector/common/CommonCollector.scala
  modules/collector-common/src/main/scala/io/janstenpickle/trace4cats/collector/common/Http4sJdkClient.scala
  modules/collector-common/src/main/scala/io/janstenpickle/trace4cats/collector/common/Sampling.scala
  modules/collector-common/src/main/scala/io/janstenpickle/trace4cats/collector/common/Tracing.scala
  modules/collector-common/src/main/scala/io/janstenpickle/trace4cats/collector/common/config/CommonCollectorConfig.scala
  modules/collector-common/src/main/scala/io/janstenpickle/trace4cats/collector/common/config/ConfigParser.scala
  modules/collector-common/src/main/scala/io/janstenpickle/trace4cats/collector/common/config/package.scala
  modules/collector-lite/src/main/docker/build.sh
  modules/collector-lite/src/main/scala/io/janstenpickle/trace4cats/collector/CollectorLite.scala
  modules/collector/src/main/scala/io/janstenpickle/trace4cats/collector/Collector.scala
  modules/collector/src/main/scala/io/janstenpickle/trace4cats/collector/config/CollectorConfig.scala
  project/Dependencies.scala
  project/build.properties
  project/plugins.sbt
Labels: skip-changelog

#3 Update grpc-okhttp to 1.38.1
  project/Dependencies.scala
Labels: dependency-update

#1 Update circe-yaml to 0.14.0
  project/Dependencies.scala
Labels: dependency-update

#11 Update grpc-okhttp to 1.39.0
  project/Dependencies.scala
Labels: dependency-update

#16 Update Mergify rules
  .github/mergify.yml
Labels: skip-changelog

#18 Fix Mergify rules
  .github/mergify.yml
Labels: skip-changelog

#17 Update decline-effect to 2.1.0
  project/Dependencies.scala
Labels: dependency-update

#22 Fix docker push for tagged releases
  .github/workflows/ci.yml
  ci-release.sbt
Labels: ready-to-merge, skip-changelog, skip-release

#23 Add Dockerhub badge to README
  README.md
Labels: ready-to-merge, skip-changelog, skip-release

#24 Update sbt-ci-release-early to 2.0.17
  project/plugins.sbt
Labels: dependency-update

#25 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#26 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#27 Update logback-classic to 1.2.4
  project/Dependencies.scala
Labels: dependency-update

#28 Update logback-classic to 1.2.5
  project/Dependencies.scala
Labels: dependency-update

#29 Fix push for tagged release
  .github/workflows/ci.yml
  ci-release.sbt
Labels: ready-to-merge, skip-changelog, skip-release
